version: "3.8"

services:
  hsa1015-nginx:
    container_name: hsa1015-nginx
    image: macbre/nginx-http3:1.25.2
    restart: always
    ports:
      - 9044:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/GeoLite2-Country.mmdb:/var/geo/GeoLite2-Country.mmdb